ukparliament/parliament.uk-pugin

Makefile
=> Removing an environmental variable

src/javascripts/content_slider.js, src/javascripts/hasJS.js
* separated functions to independent files
=> [WEBSITE-459] Review and update JavaScript file - [parliament.uk-pugin]

index.pug, src/components/letter-navigation.pug, src/elements/mixins.pug, src/layouts/layout.pug, src/stylesheets/components/_link-button.scss, src/stylesheets/components/_list-styles.scss, src/stylesheets/components/_navigation-letter.scss, src/templates/members/house-commons-members-current.pug, src/templates/members/house-lords-members-current.pug, src/templates/members/party-current.pug, src/templates/members/people-members-current.pug
[WEBSITE-422] Pug component refactoring on navigation, lists and buttons
[WEBSITE-423] SASS refactoring on navigation, lists and buttons
=> [WEBSITE-422][WEBSITE-423] Pug & SASS refactoring

Makefile
- #### Added variables for shell script
- #### Removed unnecessary AWS comments
=> [WEBSITE-316] versioned pugin assets

src/components/footer.pug, src/components/header.pug, src/components/status.pug, src/stylesheets/components/_footer.scss, src/stylesheets/components/_header.scss, src/stylesheets/components/_highlight-box.scss, src/stylesheets/components/_highlight-status.scss, src/stylesheets/elements/_links.scss, src/stylesheets/elements/_typography.scss, src/stylesheets/settings/_colours.scss, src/templates/prototypes/people-id.pug
amended old components to fit new designs
added new styles to represent pugin branding
adjusted old template to represent new designs
=> [WEBSITE-712] Updates to prototypes to represent new design

Makefile
=> [WEBSITE-630]-create a release for parliament.uk-pugin

src/stylesheets/components/_footer.scss, src/stylesheets/components/_header.scss, src/stylesheets/components/_highlight-box.scss, src/stylesheets/components/_highlight-status.scss, src/stylesheets/components/_line-break.scss, src/stylesheets/components/_link-tab.scss, src/stylesheets/components/_list-styles.scss, src/stylesheets/components/_navigation-letter.scss, src/stylesheets/elements/_links.scss, src/stylesheets/elements/_typography.scss, src/stylesheets/objects/_block-layouts.scss, src/stylesheets/objects/_grid-layouts.scss, src/stylesheets/settings/_colours.scss, src/stylesheets/settings/_spacing.scss, src/stylesheets/tools/mixins/_font-size.scss, src/templates/prototypes/conservative-current.pug, src/templates/prototypes/contact.pug, src/templates/prototypes/front-page.pug, src/templates/prototypes/house-commons-members-current.pug, src/templates/prototypes/house-lords-members-current.pug, src/templates/prototypes/party-current.pug
- Colour palette updated to reflect new brand
- Component updates including letter navigation, header, footer and status banner
- Updates to spacing units
- Enhancements to block layout components
- Enhancements to SASS mixins
- Updating static templates to reflect new brand and designs
=> [WEBSITE-712] SASS & Static template updates for new brand designs

src/components/header.pug, src/stylesheets/components/_header.scss, src/stylesheets/elements/_typography.scss
- #### [WEBSITE-806] Removed unnecessary span within header
- #### [WEBSITE-789] Refactoring of typography
=> [WEBSITE-806][WEBSITE-789] Refactoring of markup/css

src/components/footer.pug, src/components/status.pug, src/stylesheets/components/_footer.scss, src/stylesheets/components/_highlight-status.scss, src/stylesheets/elements/_body.scss, src/stylesheets/elements/_links.scss, src/stylesheets/elements/_typography.scss
Updates to footer styling and template
Updates to status banner styling and template
Font smoothing & feature settings added to body
=> [WEBSITE-809][WEBSITE-778] Footer & status banner styling

src/components/header.pug, src/layouts/layout.pug, src/stylesheets/components/_content-slider.scss, src/stylesheets/components/_footer.scss, src/stylesheets/components/_header.scss, src/stylesheets/components/_highlight-box.scss, src/stylesheets/components/_highlight-status.scss, src/stylesheets/components/_line-break.scss, src/stylesheets/components/_link-tab.scss, src/stylesheets/components/_list-styles.scss, src/stylesheets/components/_navigation-letter.scss, src/stylesheets/elements/_body.scss, src/stylesheets/elements/_form.scss, src/stylesheets/elements/_headings.scss, src/stylesheets/elements/_links.scss, src/stylesheets/elements/_lists.scss, src/stylesheets/elements/_logos.scss, src/stylesheets/elements/_media.scss, src/stylesheets/elements/_semantic-elements.scss, src/stylesheets/elements/_tables.scss, src/stylesheets/elements/_typography.scss, src/stylesheets/main.scss, src/stylesheets/objects/_block-layouts.scss, src/stylesheets/objects/_grid-layouts.scss, src/stylesheets/settings/_colours.scss, src/stylesheets/settings/_fonts.scss, src/stylesheets/settings/_spacing.scss, src/stylesheets/trumps/_helpers.scss, src/templates/prototypes/contact.pug, src/templates/prototypes/front-page.pug
* Colours refactored and reapplied
* Headings, typography file separation
* Spacing units refactored
* Templates updated with latest content and layout
=> [WEBSITE-911] SCSS & template markup refactoring

src/components/letter-navigation.pug, src/components/number-navigation.pug, src/stylesheets/components/_navigation.scss, src/stylesheets/main.scss, src/templates/prototypes/search-results.pug
[WEBSITE-911] Refactoring of navigation.scss
[WEBSITE-964] Base commit for pagination
- Created number-navigation component
- Created base search result prototype template
- Refactored navigation
=> [WEBSITE-964][WEBSITE-911] Base commit for pagination

src/stylesheets/components/_navigation.scss
* fixed A to Z text transformation
=> [WEBSITE-1069] Navigation variation

src/stylesheets/components/_navigation.scss
* unable to compile scss, missing closing tag
=> fix: [WEBSITE-1069]

index.pug, scripts/w3c.js, server.js, src/templates/prototypes/conservative-current.pug, src/templates/prototypes/house-commons-members-current.pug, src/templates/prototypes/house-lords-members-current.pug, src/templates/prototypes/party-current.pug
* fixed w3c validation for favicon
* fixed w3c validation for missing content anchor (skip link)
* updated the app port for our w3c tests
* converted js files from es* to vanilla js
* fixed w3c validation for 'li' within 'div'
=> [WEBSITE-1216] [WEBSITE-1217] Accessibility fixes & Coding standard

src/stylesheets/components/_highlight.scss, src/stylesheets/elements/_media.scss, src/stylesheets/objects/_content-layouts.scss, src/templates/index.pug, src/templates/prototypes/conservative-current.pug, src/templates/prototypes/constituencies.pug, src/templates/prototypes/contact.pug, src/templates/prototypes/forms.pug, src/templates/prototypes/front-page.pug, src/templates/prototypes/house-commons-members-current.pug, src/templates/prototypes/house-lords-members-current.pug, src/templates/prototypes/navigation.pug, src/templates/prototypes/party-current.pug, src/templates/prototypes/people-constituency.pug, src/templates/prototypes/people-id.pug
* Highlights to target all child elements
* Responsive rules added for images within section--primary
* Addition of section--primary__container to handle floating elements
* Updated all templates to new section--primary structure
=> [WEBSITE-1195] Second implementation of members images

src/components/input.pug, src/elements/mixins.pug, src/templates/prototypes/forms.pug
* Included maxlength attribute
* Included a regex pattern to validate against
* Created a input mixin
=> [WEBSITE-1225] Client-side validation for postcode

src/stylesheets/elements/_form.scss, src/stylesheets/elements/_typography.scss
[WEBSITE-1164] HTML form element refactoring
[WEBSITE-1149] Ensure HTML form elements use correct font stack
=> [WEBSITE-1149][WEBSITE-1164] HTML form refactoring

.eslintrc.js, src/elements/mixins.pug, src/javascripts/button_state.js, src/javascripts/hasJS.js, src/templates/prototypes/forms.pug
- Updated client-side validation to stop button loading animation when input is not valid
=> [WEBSITE-1225] Added client-side validation

.eslintrc.js, src/javascripts/button_state.js
* Updated when event listener is executed
* updated eslint
=> [WEBSITE-1225] Fix: client-side validation

src/javascripts/button_state.js, src/templates/prototypes/forms.pug
* Loading visualisation added to postcode finder instead of search
* Strict equality comparison operators added to button_state script
* Correct width and height added to SVG viewBox
=> [WEBSITE-1156] Postcode visualisation feature improvements

package-lock.json, src/stylesheets/components/_navigation.scss
* Also added in package.lock.json
=> [WEBSITE-1313] remove outline on main-nav focus state

src/stylesheets/elements/_typography.scss, src/stylesheets/objects/_content-layouts.scss, src/stylesheets/settings/_fonts.scss, src/templates/index.pug, src/templates/prototypes/containers.pug
Also updated font-size for labels
=> [WEBSITE-1419][WEBSITE-1449] Prototyped inner container with white background

Makefile, package.json
Update NPM modules for bugfixing and security fixes.
=> Update NPM modules

server.js, src/components/header.pug, src/elements/head.pug, src/layouts/layout-front-page.pug, src/layouts/layout.pug, src/templates/index.pug, src/templates/prototypes/conservative-current.pug, src/templates/prototypes/house-commons-members-current.pug, src/templates/prototypes/house-lords-members-current.pug, src/templates/prototypes/lists.pug, src/templates/prototypes/people-id.pug
=> [WEBSITE-1563] static assets path

src/javascripts/map.js, src/templates/prototypes/map.pug
=> [WEBSITE-1576] Map height fix

src/stylesheets/components/_dropdown.scss, src/stylesheets/components/_highlight.scss, src/stylesheets/components/_list-styles.scss, src/stylesheets/objects/_content-layouts.scss, src/templates/prototypes/people-id.pug
=> [WEBSITE-1620] Section margin fix

src/components/mapbox.pug, src/elements/_elements.pug, src/elements/_mapbox.pug, src/layouts/layout-front-page.pug, src/layouts/layout.pug, src/stylesheets/components/_list-styles.scss, src/templates/prototypes/_map.pug, src/templates/prototypes/constituency.pug
* create map mixin
* grouped mixins into a single reference file
* aligned tabs
=> [WEBDEV-126][WEBSITE-1680] map mixin & tabs alignment

src/elements/_lists.pug, src/stylesheets/elements/_media.scss, src/stylesheets/settings/_accents.scss, src/stylesheets/settings/_mixins.scss, src/stylesheets/settings/_themes.scss, src/templates/index.pug, src/templates/prototypes/backgrounds.pug, src/templates/prototypes/media-id.pug, src/templates/prototypes/people-id.pug
…ge and updated media to use responsive images
=> [WEBDEV-179][WEBDEV-177][WEBDEV-124] Theme updates with background page and updated media to use responsive images

src/components/lists/list--box.pug, src/components/status.pug, src/elements/_lists.pug, src/stylesheets/components/_list-styles.scss, src/stylesheets/elements/_media.scss, src/templates/prototypes/_lists.pug, src/templates/prototypes/conservative-current.pug, src/templates/prototypes/constituencies.pug, src/templates/prototypes/constituency.pug, src/templates/prototypes/front-page.pug, src/templates/prototypes/house-commons-members-current.pug, src/templates/prototypes/house-lords-members-current.pug, src/templates/prototypes/media-id.pug, src/templates/prototypes/party-current.pug, src/templates/prototypes/people-constituency.pug, src/templates/prototypes/people-id.pug
- Renamed list box component
-  Updated status banner
- Added list media mixin and updated templates
- Added templates using list pipe
=> [WEBDEV-178][WEBDEV-181][WEBDEV-182] Updates to list pipe mixins

src/stylesheets/elements/_headings.scss, src/templates/index.pug, src/templates/prototypes/_timeline.pug
- Added view for Timeline component
- Updated Time heading colour
- Re-order Elements list on index page
=> [WEBSITE-1927] Added a timeline view and update the heading colours

src/stylesheets/components/_highlight.scss, src/stylesheets/elements/_body.scss, src/stylesheets/elements/_typography.scss, src/stylesheets/settings/_mixins.scss, src/stylesheets/settings/_themes.scss, src/templates/prototypes/_backgrounds.pug
- Removed ```<p>``` specific line-height and font-size styling
- Included new deep-purple--light theme
- Added status--highlights to backgrounds template
=> [WEBSITE-1972] Status banner updates for cookie implementation

src/stylesheets/components/_buttons.scss, src/stylesheets/components/_list-styles.scss, src/stylesheets/elements/_form.scss, src/templates/prototypes/_buttons-forms.pug, src/templates/prototypes/_forms.pug, src/templates/prototypes/_lists.pug
[WEBDEV-238] 'btn--grey' button style added
[WEBDEV-304] Bottom margin applied to input with type of 'text'
[WEBDEV-301] Top margin applied to button with type of 'submit'
[WEBDEV-298][WEBDEV-305] Ordered numbered, roman numeral and alphabetical lists added
=> [WEBDEV-238][WEBDEV-298][WEBDEV-301][WEBDEV-304][WEBDEV-305] Form & List enhancements

src/javascripts/map.js
- Changed map id to 'streets'
- Move zoom control to 'bottomright'
=> [WEBSITE-2111] [WEBSITE-2112] Changed map tile and repositioned zoom control

Makefile, package-lock.json, package.json, src/images/fullscreen_close.svg, src/images/fullscreen_open.svg, src/javascripts/map.js, src/stylesheets/components/_map.scss
- Changed map tile from 'light' to 'streets'
- Moved zoom control from 'topleft' to 'bottomright'
- Add fullscreen plugin and control
- Branded controls
=> [WEBSITE-2111][WEBSITE-2112][WEBSITE-2133][WEBSITE-2134] Updated map

Makefile, src/stylesheets/components/_footer.scss, src/stylesheets/elements/_body.scss, src/stylesheets/elements/_semantic-elements.scss, src/stylesheets/main.scss
=> [WEBDEV-418] Implementation of pugin-core

src/elements/_form.pug, src/stylesheets/elements/_form.scss, src/stylesheets/elements/_typography.scss, src/templates/prototypes/_forms.pug
* [WEBDEV-408] Form error messaging
* [WEBDEV-410] Refactoring select input
* [WEBDEV-411] Input group variation verbose added
* [WEBDEV-412] Refactoring hero rules
* [WEBDEV-413] Refactoring standard lists
* [WEBDEV-414] Additional Status Highlight Rules
=> [WEBDEV-408][WEBDEV-410][WEBDEV-411][WEBDEV-412][WEBDEV-413][WEBDEV-414] Form, List and Highlight Updates

src/stylesheets/elements/_semantic-elements.scss
Flex alone does not work in IE11
=> [Fix] IE11 fix for sticky footer

src/stylesheets/elements/_form.scss
* [WEBDEV-419] Radio & checkbox positioning
* [WEBDEV-424] Radio group colour inversion
* [WEBDEV-429] Form element focus styles
=> [WEBDEV-419][WEBDEV-424][WEBDEV-429] Form element styling updates

src/stylesheets/components/_article.scss, src/stylesheets/components/_buttons.scss, src/stylesheets/components/_dropdown.scss, src/stylesheets/components/_highlight.scss, src/stylesheets/components/_hints.scss, src/stylesheets/components/_list-styles.scss, src/stylesheets/components/_map.scss, src/stylesheets/components/_navigation.scss, src/stylesheets/components/_tracks.scss, src/stylesheets/elements/_body.scss, src/stylesheets/elements/_form.scss, src/stylesheets/elements/_headings.scss, src/stylesheets/elements/_links.scss, src/stylesheets/elements/_media.scss, src/stylesheets/elements/_tables.scss, src/stylesheets/elements/_typography.scss, src/stylesheets/objects/_content-layouts.scss, src/stylesheets/settings/_mixins.scss, src/stylesheets/settings/_spacing.scss, src/templates/prototypes/_lists.pug, src/templates/prototypes/people-id.pug
- Abstraction of font sizes from headers for re-usability across components
- Enhancement to alternative sizes
- Compiled list of all component margins to single manageable file
- HTML element includes the body font size to enable increment/decrement
=> [Refactoring] - Global typography implementation

src/stylesheets/components/_article.scss, src/stylesheets/components/_aside.scss, src/stylesheets/components/_header.scss, src/stylesheets/objects/_content-layouts.scss, src/stylesheets/settings/_mixins.scss, src/templates/prototypes/_article.pug, src/templates/prototypes/article.pug
- Using flex styles instead of position absolute on the sidebar
- Changed flex-basis for flex styles with width instead, which lets content display correctly in IE10
- Removed header tag styles inside articles as they're not required at the moment
=> [WEBDEV-505] Bug fix for article sidebar

src/elements/skip-content.pug, src/stylesheets/settings/_mixins.scss, src/stylesheets/trumps/_helpers.scss, test/paths.json
- Added padding to classes with `.sr-only` to make it clickable on android.
- Created a separate class for 'Skip to content' link for additional styles extending the `.sr-only` class.
=> [WEBDEV-506] Make .sr-only more accessible

Makefile, postcss.config.js, src/stylesheets/pugin-base.scss
This:
- Removes unused variables
- Merges CSS tasks so the processes don't need to duplicate
- Enables compression on JavaScript via UglifyJS
- Extrapolates PostCSS configuration from the command line
=> Clean up Makefile

package-lock.json, package.json, postcss.config.js, src/stylesheets/objects/_content-layouts.scss
* Merge same media queries into one
* Improve css minification using cssnano
=> [WEBDEV-527] Merge media queries and improved minification

.travis.yml, package-lock.json, package.json, postcss.config.js, src/stylesheets/components/_list-styles.scss, src/stylesheets/elements/_headings.scss, src/stylesheets/elements/_typography.scss, src/stylesheets/settings/_mixins.scss
* Updated Typograpghy
* Removed css-mqpacker because it failed to merge queries in some instances
=> [WEBDEV-529] Set global paragraph typography & Removed css-mqpacker

src/stylesheets/components/_article.scss, src/stylesheets/components/_card.scss, src/stylesheets/elements/_headings.scss, src/stylesheets/elements/_typography.scss, src/stylesheets/settings/_mixins.scss
* [OUT-260] Updated line lengths
* [OUT-261] Fixed print utility flex-basis width issue on IE
=> [OUT-260] [OUT-261] Fixed, print and line lengths

src/stylesheets/components/_article.scss, src/stylesheets/components/_aside.scss, src/stylesheets/components/_card.scss, src/stylesheets/components/_header.scss, src/stylesheets/components/_highlight.scss, src/stylesheets/components/_line-break.scss, src/stylesheets/components/_list-styles.scss, src/stylesheets/components/_map.scss, src/stylesheets/components/_navigation.scss, src/stylesheets/elements/_form.scss, src/stylesheets/elements/_headings.scss, src/stylesheets/elements/_icons.scss, src/stylesheets/elements/_links.scss, src/stylesheets/elements/_logos.scss, src/stylesheets/elements/_tables.scss, src/stylesheets/elements/_typography.scss, src/stylesheets/objects/_content-layouts.scss, src/stylesheets/objects/_grid-settings.scss, src/stylesheets/settings/_mixins.scss, src/stylesheets/settings/_spacing.scss, src/templates/prototypes/front-page.pug, src/templates/prototypes/guide-to-procedures.pug
- Updated breakpoint names
- Removed JC's max-width
- Added styles for aside at different break points
-  Updated Hero offset
- Added offset's for sections
- Updated template: front page
=> [WEBDEV-556] Updated layout

package-lock.json, src/stylesheets/components/_dropdown.scss, src/stylesheets/components/_tracks.scss, src/stylesheets/elements/_headings.scss, src/templates/prototypes/_tracks.pug, src/templates/prototypes/people-id.pug
* Tracks component refactored into correct list item structure
* Track margins and nested heading margins refactored
* Options added for track headings to have typography weight variants
=> [WEBDEV-492] Restructuring of tracks component

src/javascripts/toggle.js
- Will look into improving this code further in the near future.
- Handling toggles within toggles for hybrid bills in existing code-base.
- Removed active state on buttons at the moment it is not needed.
=> [WEBDEV-586] Make toggles within toggles independent from parent toggle

package-lock.json, src/elements/head.pug, src/stylesheets/components/_article.scss, src/stylesheets/elements/_headings.scss, src/stylesheets/elements/_typography.scss, src/templates/prototypes/_article.pug, src/templates/prototypes/_backgrounds.pug, src/templates/prototypes/_buttons.pug, src/templates/prototypes/_forms.pug, src/templates/prototypes/_headings.pug, src/templates/prototypes/_icons.pug, src/templates/prototypes/_lists.pug, src/templates/prototypes/_map.pug, src/templates/prototypes/_navigations.pug, src/templates/prototypes/_tables.pug, src/templates/prototypes/_toggles.pug, src/templates/prototypes/_tracks.pug, src/templates/prototypes/conservative-current.pug, src/templates/prototypes/constituencies.pug, src/templates/prototypes/constituency.pug, src/templates/prototypes/front-page.pug, src/templates/prototypes/guide-to-procedures.pug, src/templates/prototypes/house-commons-members-current.pug, src/templates/prototypes/house-lords-members-current.pug, src/templates/prototypes/media-id.pug, src/templates/prototypes/party-current.pug, src/templates/prototypes/people-constituency.pug, src/templates/prototypes/people-id.pug, src/templates/prototypes/questions.pug, src/templates/prototypes/search-results.pug
Updated H1 based on the model identified in the Utilities working group. No errors have been identified in my current testing done using Voiceover and Chromevox, we will also need to plan in testing with the assisstance of DAC to ensure there are no other unforeseen implications, these enhancements can then be included.
=> Modelling of H1s

src/stylesheets/elements/_headings.scss
- Changes as requested by Victor
=> h1 modelling design enhancements

src/stylesheets/settings/_mixins.scss
Greetings from Belize,
I was stealing the theme concept for a piece of work it fitted and your incorrect comments confused me :/. Also needs to be fixed in the themes file. 
Chris
=> Update comments for theme mixin

src/stylesheets/components/_list-styles.scss, src/stylesheets/settings/_mixins.scss, src/templates/prototypes/_lists.pug, src/templates/prototypes/front-page.pug
- Created mixin to calculate columns
- Updated front page
=> [WEBDEV-610] Refactored list--2 and 3

src/stylesheets/components/_list-styles.scss
Issue: list--3 within non section--wide spanned full width, it should be two columns
=> [bugfix] Updated list--3

postcss.config.js, src/stylesheets/elements/_links.scss
- Resolve cssnano mergeLonghand properties issue
- Fix figure hover effect on browsers
- Reduce figure link opacity
=> Minor bug fixes

src/stylesheets/elements/_media.scss
Quick fix to the broken video height issue
=> [Bug] Re-apply video wrapper class

package-lock.json, src/components/status__beta.pug, src/stylesheets/components/_highlight.scss, src/stylesheets/components/_hints.scss, src/stylesheets/components/_list-styles.scss, src/stylesheets/objects/_content-layouts.scss
- Remove status--banner__beta
- Replace li within status_banner with a p tag
=> [WEBDEV-658] Standardise status banner

package-lock.json, package.json, src/components/navigation-number.pug, src/components/status__beta.pug, src/elements/head.pug, src/stylesheets/legacy.scss, src/templates/prototypes/_legacy.pug, src/templates/prototypes/search-results.pug
- Introduce a legacy style sheet
- Re-introduce .status--banner__beta
- Re-introduce prior .navigation--number markup and style
=> Reintroduce legacy styles

package-lock.json, src/elements/head.pug, src/stylesheets/components/_list-styles.scss
- Fix Legacy.css override
- Version bump
=> [Fix] Legacy style and Version bump

package-lock.json, src/stylesheets/elements/_form.scss
=> [WEBDEV-605] Fix global search alignment

src/components/header.pug, src/javascripts/search.js, src/stylesheets/components/_buttons.scss, src/stylesheets/components/_header.scss, src/stylesheets/elements/_form.scss, src/stylesheets/elements/_icons.scss, src/stylesheets/elements/_links.scss
- Significant refactoring made to header search scss files allowing the removal of `.search__global` wrapper in order to reduce complexity for componentization.
- Multiple tasks of creating a list of draw calls and rasterization reduced by removing transitions.
=> [WEBDEV-713] Refactoring of global search

package-lock.json, package.json, src/stylesheets/elements/_media.scss, src/stylesheets/legacy.scss, src/stylesheets/objects/_content-layouts.scss, src/stylesheets/settings/_mixins.scss, src/templates/prototypes/article.pug
- Refactor article
- Fix legacy article
- Pugin version bump
=> [WEBDEV-1121] Refactor article

package-lock.json, src/stylesheets/main.scss, src/templates/prototypes/_buttons.pug, src/templates/prototypes/_forms.pug
* update build order of child SASS files in main.scss so that normalize reset styles are declared first.
* consolidate element attributes on forms and buttons templates
=> [WEBDEV-1137] Updates to main SASS file and templates
